### ISSUE TITLE
Parameter -p in seam carving works in opposite manner

### ISSUE THREAD

**Issue by elbertronnie** [hs2361/k-means-compressor#16]
Currently the Usage section of the cli states that the -p parameter in seam carving command is the percentage of width to be reatined but the program instead cuts that much percentage from the image.

Example: 
`./compressor -s -i input.png -o output.png -p 0.3` will cut 30% rather than retaining 30%.

**Comment by hs2361** [comment]
Good catch @elbertronnie! We must have written that accidentally in the README. Thanks for raising this issue.
