### ISSUE TITLE
[FEATURE] Remove bits/stdc++.h

### ISSUE THREAD

**Issue by DebadityaPal** [hs2361/k-means-compressor#4]
The bits/stdc++.h header file used is a nonstandard header file that might not work with non-GNU compilers like Clang. Hence, we should get rid of it.
Try to import the header dependencies individually and remove all instances of bits/stdc++.h

**Comment by XDRAGON2002** [comment]
I would like to work on this issue

**Comment by DebadityaPal** [comment]
Assigned.

**Comment by XDRAGON2002** [comment]
I can't seem to get the program to even compile even though I have gcc version 11.1.0. So could I be provided with an example command that is guaranteed to run without throwing any errors ?

**Comment by DebadityaPal** [comment]
Send the error traceback. It makes it easier for us to figure out the error.
Also did you set the C++17 flag, like this?
`gcc -std=C++17 compressor.cpp <args>`

**Comment by XDRAGON2002** [comment]
I've edited my previous comment, do check it out.

**Comment by DebadityaPal** [comment]
Tagging @hs2361 for visibility. @XDRAGON2002, try using `g++ -std=c++17 compressor.cpp -o compressor `. There is a documentation error indeed, if you want you can update it in the docs as well, otherwise, I'll do it. Feel free to raise an issue.

**Comment by XDRAGON2002** [comment]
@DebadityaPal yes the updated command works as expected, I'll be sure to raise and fix the documentation issue once I'm finished with this issue.
Also just for the sake of it, any idea why the gcc compiler might behave this way ? Not being able to link files ?

**Comment by DebadityaPal** [comment]
So the gcc compiler is basically a simplified version of the g++ compiler.
In simple terms:
`g++` = `gcc -xc++ -lstdc++ -shared-libgcc`
where the first arg is a compiler and the other 2 are linkers.
Check out this [Stackoverflow Question](https://stackoverflow.com/questions/172587/what-is-the-difference-between-g-and-gcc) for a much more detailed answer

**Comment by XDRAGON2002** [comment]
Oh okay that explains a lot. Thanks for the quick response though !

**Comment by XDRAGON2002** [comment]
Also created #8 regarding the documentation fix.

**Comment by DebadityaPal** [comment]
No problem, but unfortunately I can't add that issue to the hacktoberfest topic as it is a very small issue. I'm afraid their reviewers would mark it as spam. But it would count towards the Git Init FOSS leaderboard though.

**Comment by XDRAGON2002** [comment]
Sure, it's okay.

**Comment by XDRAGON2002** [comment]
Opened PR #9 fixing this issue.
